function CSpriteLibrary(){var a,d,e,h,k,c;this.init=function(f,g,b){e=d=0;h=f;k=g;c=b;a={}};this.addSprite=function(c,g){a.hasOwnProperty(c)||(a[c]={szPath:g,oSprite:new Image},d++)};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){k.call(c)};this._onSpriteLoaded=function(){h.call(c);++e===d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in a)a[c].oSprite.oSpriteLibrary=this,a[c].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[c].oSprite.src=a[c].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1024,CANVAS_HEIGHT=768,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,GAME_STATE_IDLE=0,GAME_STATE_SPINNING=1,GAME_STATE_SHOW_ALL_WIN=2,GAME_STATE_SHOW_WIN=3,REEL_STATE_START=0,REEL_STATE_MOVING=1,REEL_STATE_STOP=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,REEL_OFFSET_X=142,REEL_OFFSET_Y=148,NUM_REELS=5,NUM_ROWS=3,NUM_SYMBOLS=8,WILD_SYMBOL=8,NUM_PAYLINES=20,SYMBOL_SIZE=140,SPACE_BETWEEN_SYMBOLS=
10,MAX_FRAMES_REEL_EASE=16,MIN_REEL_LOOPS,REEL_DELAY,REEL_START_Y=REEL_OFFSET_Y-3*SYMBOL_SIZE,REEL_ARRIVAL_Y=REEL_OFFSET_Y+3*SYMBOL_SIZE,TIME_SHOW_WIN,TIME_SHOW_ALL_WINS,MIN_BET=.05,MAX_BET=.5,TOTAL_MONEY;
function CTweenController(){this.tweenValue=function(a,d,e){return a+e*(d-a)};this.easeLinear=function(a,d,e,h){return e*a/h+d};this.easeInCubic=function(a,d,e,h){h=(a/=h)*a*a;return d+e*h};this.easeBackInQuart=function(a,d,e,h){h=(a/=h)*a;return d+e*(2*h*h+2*h*a+-3*h)};this.easeInBack=function(a,d,e,h){return e*(a/=h)*a*(2.70158*a-1.70158)+d};this.easeOutCubic=function(a,d,e,h){return e*((a=a/h-1)*a*a+1)+d}}
function CToggle(a,d,e){var h,k,c;this._init=function(a,g,b){h=[];k=[];b=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{on:[0,1],off:[1,2]}});c=s_bAudioActive?new createjs.Sprite(b,"on"):new createjs.Sprite(b,"off");c.x=a;c.y=g;c.stop();s_oStage.addChild(c);this._initListener()};this.unload=function(){c.off("mousedown",this.buttonDown);c.off("pressup",this.buttonRelease);s_oStage.removeChild(c)};this._initListener=function(){c.on("mousedown",
this.buttonDown);c.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){h[a]=c;k[a]=b};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");c.scaleX=1;c.scaleY=1;(s_bAudioActive=!s_bAudioActive)?c.gotoAndStop("on"):c.gotoAndStop("off");h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=function(){c.scaleX=.9;c.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this._init(a,d,e)}
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,d=CANVAS_HEIGHT,e=window.innerWidth;multiplier=Math.min(window.innerHeight/d,e/a);a*=multiplier;d*=multiplier;$("#canvas").css("width",a+"px");$("#canvas").css("height",d+"px");$("#canvas").css("left",e/2-a/2+"px")}}function randomFloatBetween(a,d,e){"undefined"===typeof e&&(e=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(e))}
function shuffle(a){for(var d=a.length,e,h;0!==d;)h=Math.floor(Math.random()*d),d-=1,e=a[d],a[d]=a[h],a[h]=e;return a}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var e="",e=10>d?e+("0"+d+":"):e+(d+":");return e=10>a?e+("0"+a):e+a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
function CTextButton(a,d,e,h,k,c,f){var g,b,t,r,q,m,p,n,v;this._init=function(a,c,f,h,d,l,k){g=!1;r=[];q=[];v=new createjs.Bitmap(f);b=f.width;t=f.height;var A=Math.ceil(k/20);p=new createjs.Text(h,"bold "+k+"px "+d,"#000000");p.textAlign="center";var e=p.getBounds();p.x=f.width/2+A;p.y=(f.height-e.height)/2+A;n=new createjs.Text(h,"bold "+k+"px "+d,l);n.textAlign="center";e=n.getBounds();n.x=f.width/2;n.y=(f.height-e.height)/2;m=new createjs.Container;m.x=a;m.y=c;m.regX=f.width/2;m.regY=f.height/
2;m.addChild(v,p,n);s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown");m.off("pressup");s_oStage.removeChild(m)};this.setVisible=function(a){m.visible=a};this.enable=function(){g=!1;v.filters=[];v.cache(0,0,b,t)};this.disable=function(){g=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);v.filters=[new createjs.ColorMatrixFilter(a)];v.cache(0,0,b,t)};this._initListener=function(){oParent=this;m.on("mousedown",this.buttonDown);m.on("pressup",
this.buttonRelease)};this.addEventListener=function(a,c,b){r[a]=c;q[a]=b};this.buttonRelease=function(){g||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),m.scaleX=1,m.scaleY=1,r[ON_MOUSE_UP]&&r[ON_MOUSE_UP].call(q[ON_MOUSE_UP]))};this.buttonDown=function(){g||(m.scaleX=.9,m.scaleY=.9,r[ON_MOUSE_DOWN]&&r[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN]))};this.setPosition=function(a,c){m.x=a;m.y=c};this.changeText=function(a){n.text=a;p.text=a};this.setX=function(a){m.x=a};this.setY=
function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this._init(a,d,e,h,k,c,f);return this}
function CStaticSymbolCell(a,d,e,h){var k=-1,c,f,g,b;this._init=function(a,c,h,d){b=new createjs.Container;b.visible=!1;f=[];for(a=0;a<NUM_SYMBOLS;a++)c=new createjs.Sprite(s_aSymbolAnims[a],"static"),c.stop(),c.x=h,c.y=d,c.on("animationend",this._onAnimEnded,null,!1,{index:a}),b.addChild(c),f[a]=c,f[a].visible=!1;a={framerate:60,images:[s_oSpriteLibrary.getSprite("win_frame_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,19]}};a=new createjs.SpriteSheet(a);
g=new createjs.Sprite(a,"static");g.stop();g.x=h;g.y=d;b.addChild(g);s_oStage.addChild(b)};this.unload=function(){s_oStage.removeChild(b)};this.hide=function(){-1<k&&(g.gotoAndStop("static"),g.visible=!1,f[k].gotoAndPlay("static"),b.visible=!1)};this.show=function(a){if(!f[a-1].visible){g.gotoAndPlay("anim");g.visible=!0;for(var h=0;h<NUM_SYMBOLS;h++)f[h].visible=h+1===a?!0:!1;f[a-1].gotoAndPlay("anim");k=a-1;c=f[a-1].spriteSheet.getNumFrames();b.visible=!0}};this._onAnimEnded=function(a,b){f[b.index].currentFrame!==
c&&(f[b.index].stop(),setTimeout(function(){f[b.index].gotoAndPlay(1)},100))};this.stopAnim=function(){f[k].gotoAndStop("static");f[k].visible=!1;g.gotoAndStop("static");g.visible=!1};this._init(a,d,e,h)}
function CSlotSettings(){this._init=function(){this._initSymbolSpriteSheets();this._initPaylines();this._initSymbolWin();this._initSymbolAnims();this._initSymbolsOccurence()};this._initSymbolSpriteSheets=function(){s_aSymbolData=[];for(var a=1;a<NUM_SYMBOLS+1;a++){var d={images:[s_oSpriteLibrary.getSprite("symbol_"+a)],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],moving:[1,2]}};s_aSymbolData[a]=new createjs.SpriteSheet(d)}};this._initPaylines=function(){s_aPaylineCombo=
[[{row:1,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:1,col:4}],[{row:0,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:0,col:4}],[{row:2,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:2,col:4}],[{row:0,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:0,col:4}],[{row:2,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:2,col:4}],[{row:1,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:1,col:4}],[{row:1,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:1,col:4}],
[{row:0,col:0},{row:0,col:1},{row:1,col:2},{row:2,col:3},{row:2,col:4}],[{row:2,col:0},{row:2,col:1},{row:1,col:2},{row:0,col:3},{row:0,col:4}],[{row:1,col:0},{row:2,col:1},{row:1,col:2},{row:0,col:3},{row:1,col:4}],[{row:2,col:0},{row:0,col:1},{row:1,col:2},{row:2,col:3},{row:1,col:4}],[{row:0,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:0,col:4}],[{row:2,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:2,col:4}],[{row:0,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:0,col:4}],
[{row:2,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:2,col:4}],[{row:1,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:1,col:4}],[{row:1,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:1,col:4}],[{row:0,col:0},{row:0,col:1},{row:2,col:2},{row:0,col:3},{row:0,col:4}],[{row:2,col:0},{row:2,col:1},{row:0,col:2},{row:2,col:3},{row:2,col:4}],[{row:0,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:0,col:4}]]};this._initSymbolWin=function(){s_aSymbolWin=[[0,0,1500,2500,5E3],[0,
0,500,1E3,2E3],[0,50,100,200,500],[0,10,50,100,150],[0,10,50,100,150],[0,10,50,100,150],[0,10,50,100,150]]};this._initSymbolAnims=function(){s_aSymbolAnims=[];var a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_1_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[0]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_2_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},
animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[1]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_3_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[2]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_4_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[3]=new createjs.SpriteSheet(a);
a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_5_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[4]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_6_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[5]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_7_anim")],
frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[6]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_8_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[7]=new createjs.SpriteSheet(a)};this._initSymbolsOccurence=function(){s_aRandSymbols=[];var a;for(a=0;1>a;a++)s_aRandSymbols.push(1);for(a=0;2>a;a++)s_aRandSymbols.push(2);
for(a=0;3>a;a++)s_aRandSymbols.push(3);for(a=0;4>a;a++)s_aRandSymbols.push(4);for(a=0;4>a;a++)s_aRandSymbols.push(5);for(a=0;6>a;a++)s_aRandSymbols.push(6);for(a=0;6>a;a++)s_aRandSymbols.push(7);for(a=0;1>a;a++)s_aRandSymbols.push(8)};this._init()}var s_aSymbolData,s_aPaylineCombo,s_aSymbolWin,s_aSymbolAnims,s_aRandSymbols;
function CReelColumn(a,d,e,h){var k,c,f,g,b,t,r,q,m,p,n,v,s,u;this._init=function(a,h,d,l){f=c=k=!1;r=0;g=a;t=l;b=g<NUM_REELS?g:g-NUM_REELS;m=0;p=MAX_FRAMES_REEL_EASE;q=REEL_STATE_START;n=d;v=n+SYMBOL_SIZE*NUM_ROWS;this.initContainer(h,d)};this.initContainer=function(a,c){u=new createjs.Container;u.x=a;u.y=c;var b=0;s=[];for(var g=0;g<NUM_ROWS;g++){var f=Math.floor(Math.random()*s_aRandSymbols.length),f=new createjs.Sprite(s_aSymbolData[s_aRandSymbols[f]],"static");f.stop();f.x=0;f.y=b;u.addChild(f);
s[g]=f;b+=SYMBOL_SIZE}s_oStage.addChild(u)};this.unload=function(){s_oStage.removeChild(u)};this.activate=function(){n=u.y;v=n+SYMBOL_SIZE*NUM_ROWS;k=!0};this._setSymbol=function(a){u.removeAllChildren();for(var c=0,b=0;b<a.length;b++){var g=new createjs.Sprite(s_aSymbolData[a[b]],"static");g.stop();g.x=0;g.y=c;u.addChild(g);s[b]=g;c+=SYMBOL_SIZE}};this.restart=function(a,b){u.y=n=REEL_START_Y;v=n+SYMBOL_SIZE*NUM_ROWS;this._setSymbol(a);if(c=b){m=0;p=MAX_FRAMES_REEL_EASE;q=REEL_STATE_STOP;for(var g=
0;g<NUM_ROWS;g++)s[g].gotoAndStop("static");f=!0}else for(g=0;g<NUM_ROWS;g++)s[g].gotoAndStop("moving")};this.setReadyToStop=function(){m=0;p=MAX_FRAMES_REEL_EASE;q=REEL_STATE_STOP};this.isReadyToStop=function(){return c};this._updateStart=function(){0===m&&g<NUM_REELS&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("start_reel"));m++;m>p&&(m=0,p/=2,q++,n=u.y,v=n+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeInBack(m,0,1,p),a=s_oTweenController.tweenValue(n,v,a);u.y=a};this._updateMoving=
function(){m++;m>p&&(m=0,n=u.y,v=n+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeLinear(m,0,1,p),a=s_oTweenController.tweenValue(n,v,a);u.y=a};this._updateStopping=function(){m++;if(m>=p)k=!1,m=0,p=MAX_FRAMES_REEL_EASE,q=REEL_STATE_START,r=0,c=!1,f&&(f=!1,u.y=REEL_OFFSET_Y),s_oGame.stopNextReel();else{var a=s_oTweenController.easeOutCubic(m,0,1,p),a=s_oTweenController.tweenValue(n,v,a);u.y=a}};this.update=function(){if(!1!==k&&(r++,r>t))switch(!1===c&&u.y>REEL_ARRIVAL_Y&&s_oGame.reelArrived(g,
b),q){case REEL_STATE_START:this._updateStart();break;case REEL_STATE_MOVING:this._updateMoving();break;case REEL_STATE_STOP:this._updateStopping()}};this._init(a,d,e,h)}
function CPreloader(){var a;this._init=function(){this._onAllPreloaderImagesLoaded()};this._onPreloaderImagesLoaded=function(){};this._onAllPreloaderImagesLoaded=function(){a=new createjs.Text("","bold 22px Arial center","#ffffff");a.x=CANVAS_WIDTH/2-40;a.y=CANVAS_HEIGHT/2;s_oStage.addChild(a)};this.unload=function(){s_oStage.removeChild(a)};this.refreshLoader=function(d){a.text=d+"%"};this._init()}
function CPayTablePanel(){var a,d,e,h,k;this._init=function(){k=new createjs.Container;h=new createjs.Bitmap(s_oSpriteLibrary.getSprite("paytable"));k.addChild(h);a=[];var c,f=220,g=184;a[0]=[];for(c=0;3>c;c++){var b=new createjs.Text("X"+(5-c),"bold 26px Arial","#ffffff");b.textAlign="center";b.x=f;b.y=g;b.textBaseline="alphabetic";k.addChild(b);a[0][c]=b;g+=49}f=220;g=365;a[1]=[];for(c=0;3>c;c++)b=new createjs.Text("X"+(5-c),"bold 26px Arial","#ffffff"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline=
"alphabetic",k.addChild(b),a[1][c]=b,g+=49;f=220;g=542;a[2]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px Arial","#ffffff"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline="alphabetic",k.addChild(b),a[2][c]=b,g+=36;f=550;g=178;a[3]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px Arial","#ffffff"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline="alphabetic",k.addChild(b),a[3][c]=b,g+=36;f=550;g=360;a[4]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px Arial","#ffffff"),
b.textAlign="center",b.x=f,b.y=g,b.textBaseline="alphabetic",k.addChild(b),a[4][c]=b,g+=36;f=870;g=178;a[5]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px Arial","#ffffff"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline="alphabetic",k.addChild(b),a[5][c]=b,g+=36;f=870;g=360;a[6]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px Arial","#ffffff"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline="alphabetic",k.addChild(b),a[6][c]=b,g+=36;d=[];f=280;g=184;d[0]=[];for(c=0;3>c;c++)b=
new createjs.Text(s_aSymbolWin[0][4-c],"bold 26px Arial","#ffff00"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline="alphabetic",k.addChild(b),d[0][c]=b,g+=49;f=280;g=365;d[1]=[];for(c=0;3>c;c++)b=new createjs.Text(s_aSymbolWin[1][4-c],"bold 26px Arial","#ffff00"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline="alphabetic",k.addChild(b),d[1][c]=b,g+=49;f=280;g=542;d[2]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[2][4-c],"bold 21px Arial","#ffff00"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline=
"alphabetic",k.addChild(b),d[2][c]=b,g+=36;f=610;g=178;d[3]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[3][4-c],"bold 21px Arial","#ffff00"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline="alphabetic",k.addChild(b),d[3][c]=b,g+=36;f=610;g=360;d[4]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[4][4-c],"bold 21px Arial","#ffff00"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline="alphabetic",k.addChild(b),d[4][c]=b,g+=36;f=930;g=178;d[5]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[5][4-
c],"bold 21px Arial","#ffff00"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline="alphabetic",k.addChild(b),d[5][c]=b,g+=36;f=930;g=360;d[6]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[6][4-c],"bold 21px Arial","#ffff00"),b.textAlign="center",b.x=f,b.y=g,b.textBaseline="alphabetic",k.addChild(b),d[6][c]=b,g+=36;e=new createjs.Text(TEXT_HELP_WILD,"bold 26px Arial","#ffff00");e.textAlign="center";e.x=750;e.y=550;k.addChild(e);k.visible=!1;s_oStage.addChild(k);var t=this;k.on("pressup",function(){t._onExit()})};
this.unload=function(){var c=this;k.off("pressup",function(){c._onExit()});s_oStage.removeChild(k);for(var f=0;f<a.length;f++)k.removeChild(a[f]);for(f=0;f<d.length;f++)k.removeChild(d[f])};this.show=function(){k.visible=!0};this.hide=function(){k.visible=!1};this.resetHighlightCombo=function(){for(var c=0;c<a.length;c++)for(var f=0;f<a[c].length;f++)a[c][f].color="#ffffff",d[c][f].color="#ffff00",createjs.Tween.removeTweens(d[c][f]),d[c][f].alpha=1};this.highlightCombo=function(a,f){d[a-1][NUM_REELS-
f].color="#ff0000";this.tweenAlpha(d[a-1][NUM_REELS-f],0)};this.tweenAlpha=function(a,f){var g=this;createjs.Tween.get(a).to({alpha:f},200).call(function(){1===f?g.tweenAlpha(a,0):g.tweenAlpha(a,1)})};this._onExit=function(){s_oGame.hidePayTable()};this.isVisible=function(){return k.visible};this._init()}
function CMenu(){var a,d,e,h;this._init=function(){a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var k=s_oSpriteLibrary.getSprite("but_bg");d=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-164,k,TEXT_PLAY,"Arial","#ffffff",40);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=s_oSpriteLibrary.getSprite("audio_icon"),e=new CToggle(CANVAS_WIDTH-k.width/2+20,k.height/2+20,k),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(h);createjs.Tween.get(h).to({alpha:0},1E3).call(function(){h.visible=!1})};this.unload=function(){d.unload();d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;s_oStage.removeChild(a);a=null;s_oStage.removeChild(h);h=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._init()}
function CMain(a){var d=0,e=0,h=STATE_LOADING,k,c,f;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();s_oSpriteLibrary=new CSpriteLibrary;c=new CPreloader;this._loadImages()};
this.soundLoaded=function(){d++;d===e&&(new CSlotSettings,c.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.ogg","press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/reels.ogg",
"reels"),createjs.Sound.registerSound("./sounds/reel_stop.ogg","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.ogg","start_reel",6)):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/reels.mp3","reels"),createjs.Sound.registerSound("./sounds/reel_stop.mp3",
"reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.mp3","start_reel",6)),e+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_bg","./sprites/but_play_bg.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("paytable","./sprites/paytable.jpg");
s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("mask_slot","./sprites/mask_slot.png");s_oSpriteLibrary.addSprite("spin_but","./sprites/but_spin_bg.png");s_oSpriteLibrary.addSprite("coin_but","./sprites/but_coin_bg.png");s_oSpriteLibrary.addSprite("info_but","./sprites/but_info_bg.png");s_oSpriteLibrary.addSprite("bet_but","./sprites/bet_but.png");s_oSpriteLibrary.addSprite("win_frame_anim","./sprites/win_frame_anim.png");
s_oSpriteLibrary.addSprite("but_lines_bg","./sprites/but_lines_bg.png");s_oSpriteLibrary.addSprite("but_maxbet_bg","./sprites/but_maxbet_bg.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");for(var a=1;a<NUM_SYMBOLS+1;a++)s_oSpriteLibrary.addSprite("symbol_"+a,"./sprites/symbol_"+a+".png"),s_oSpriteLibrary.addSprite("symbol_"+a+"_anim","./sprites/symbol_"+a+"_anim.png");for(a=1;a<NUM_PAYLINES+1;a++)s_oSpriteLibrary.addSprite("payline_"+a,"./sprites/payline_"+a+".png");e+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){d++;c.refreshLoader(Math.floor(d/e*100));d===e&&(new CSlotSettings,c.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;h=STATE_MENU};this.gotoGame=function(){f=new CGame(k);h=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;h=STATE_HELP};this._update=function(a){var b=(new Date).getTime();s_iTimeElaps=
b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);h===STATE_GAME&&f.update();s_oStage.update(a)};s_oMain=this;k=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary;TEXT_GAMEOVER="GAME OVER";TEXT_CONGRATS="CONGRATULATIONS";TEXT_MONEY="MONEY";TEXT_PLAY="PLAY";TEXT_BET="BET";TEXT_COIN="COIN";
TEXT_MAX_BET="MAX BET";TEXT_INFO="INFO";TEXT_LINES="LINES";TEXT_SPIN="SPIN";TEXT_WIN="WIN";TEXT_HELP_WILD="THIS SIMBOL IS A JOLLY WHICH \nCAN REPLACE ANY OTHER \nSYMBOL TO MAKE UP A COMBO";
function CInterface(a,d,e){var h,k,c,f,g,b,t,r,q,m,p,n,v,s,u,w;this._init=function(a,d,l){var e=s_oSpriteLibrary.getSprite("but_exit");c=new CGfxButton(CANVAS_WIDTH-e.width/2-20,e.height/2+20,e,!0);c.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)t=new CToggle(c.getX()-e.width,e.height/2+20,s_oSpriteLibrary.getSprite("audio_icon")),t.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);e=s_oSpriteLibrary.getSprite("spin_but");f=new CTextButton(806+e.width/
2,642+e.height/2,e,TEXT_SPIN,"Arial","#ffffff",30);f.addEventListener(ON_MOUSE_UP,this._onSpin,this);e=s_oSpriteLibrary.getSprite("info_but");g=new CTextButton(28+e.width/2,642+e.height/2,e,TEXT_INFO,"Arial","#ffffff",30);g.addEventListener(ON_MOUSE_UP,this._onInfo,this);e=s_oSpriteLibrary.getSprite("but_lines_bg");b=new CTextButton(188+e.width/2,642+e.height/2,e,TEXT_LINES,"Arial","#ffffff",30);b.addEventListener(ON_MOUSE_UP,this._onAddLine,this);e=s_oSpriteLibrary.getSprite("coin_but");r=new CTextButton(380+
e.width/2,642+e.height/2,e,TEXT_COIN,"Arial","#ffffff",30);r.addEventListener(ON_MOUSE_UP,this._onBet,this);e=s_oSpriteLibrary.getSprite("but_maxbet_bg");q=new CTextButton(572+e.width/2,642+e.height/2,e,TEXT_MAX_BET,"Arial","#ffffff",30);q.addEventListener(ON_MOUSE_UP,this._onMaxBet,this);m=new createjs.Text("","bold 20px Arial","#000000");m.x=CANVAS_WIDTH-90;m.y=CANVAS_HEIGHT-24;m.textAlign="center";s_oStage.addChild(m);p=new createjs.Text("","bold 20px Arial","#ffffff");p.x=CANVAS_WIDTH-89;p.y=
CANVAS_HEIGHT-25;p.textAlign="center";s_oStage.addChild(p);v=new createjs.Text(TEXT_MONEY+"\n"+l.toFixed(2),"bold 30px Arial","#ffde00");v.x=140;v.y=50;v.textAlign="center";s_oStage.addChild(v);u=new createjs.Text(NUM_PAYLINES,"bold 30px Arial","#ffffff");u.x=284;u.y=CANVAS_HEIGHT-130;u.textAlign="center";u.textBaseline="alphabetic";s_oStage.addChild(u);n=new createjs.Text(a.toFixed(2),"bold 30px Arial","#ffffff");n.x=480;n.y=CANVAS_HEIGHT-130;n.textAlign="center";n.textBaseline="alphabetic";s_oStage.addChild(n);
s=new createjs.Text(TEXT_BET+": "+d.toFixed(2),"bold 30px Arial","#ffffff");s.x=690;s.y=CANVAS_HEIGHT-130;s.textAlign="center";s.textBaseline="alphabetic";s_oStage.addChild(s);w=new createjs.Text("","bold 24px Arial","#ffde00");w.x=900;w.y=CANVAS_HEIGHT-133;w.textAlign="center";w.textBaseline="alphabetic";s_oStage.addChild(w);e=s_oSpriteLibrary.getSprite("bet_but");h=[];a=e.height/2;d=148+a;l=new CBetBut(81+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,4);
h[3]=l;d+=43;l=new CBetBut(81+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,2);h[1]=l;d+=43;l=new CBetBut(81+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,20);h[19]=l;d+=43;l=new CBetBut(81+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,16);h[15]=l;d+=43;l=new CBetBut(81+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,10);h[9]=l;d+=43;l=new CBetBut(81+
e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,1);h[0]=l;d+=44;l=new CBetBut(81+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,11);h[10]=l;d+=43;l=new CBetBut(81+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,17);h[16]=l;d+=43;l=new CBetBut(81+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,3);h[2]=l;l=new CBetBut(81+e.width/2,d+43,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,
this._onBetLineClicked,this,5);h[4]=l;d=148+a;l=new CBetBut(892+e.width/2,d,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,14);h[13]=l;d+=43;l=new CBetBut(892+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,12);h[11]=l;d+=43;l=new CBetBut(892+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,9);h[8]=l;d+=43;l=new CBetBut(892+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,
this,18);h[17]=l;d+=43;l=new CBetBut(892+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,6);h[5]=l;d+=44;l=new CBetBut(892+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,7);h[6]=l;d+=43;l=new CBetBut(892+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,19);h[18]=l;d+=43;l=new CBetBut(892+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,8);h[7]=
l;d+=43;l=new CBetBut(892+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,13);h[12]=l;d+=43;l=new CBetBut(892+e.width/2,d,e,!0);l.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,15);h[14]=l;k=[];for(e=0;e<NUM_PAYLINES;e++)a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("payline_"+(e+1))),a.x=0,a.y=0,a.visible=!1,s_oStage.addChild(a),k[e]=a};this.unload=function(){c.unload();c=null;f.unload();f=null;g.unload();g=null;b.unload();b=null;r.unload();
r=null;q.unload();q=null;!1===DISABLE_SOUND_MOBILE&&(t.unload(),t=null);s_oStage.removeChild(p);s_oStage.removeChild(m);s_oStage.removeChild(s);s_oStage.removeChild(u);s_oStage.removeChild(v);s_oStage.removeChild(n);s_oStage.removeChild(w);for(var a=0;a<NUM_PAYLINES;a++)h[a].unload(),s_oStage.removeChild(k[a])};this.refreshTime=function(a){a=formatTime(a);p.text=a;m.text=a};this.refreshMoney=function(a){v.text=TEXT_MONEY+"\n"+a.toFixed(2)};this.refreshBet=function(a){n.text=a.toFixed(2)};this.refreshTotalBet=
function(a){s.text=TEXT_BET+": "+a.toFixed(2)};this.refreshNumLines=function(a){u.text=a;for(var b=0;b<NUM_PAYLINES;b++)b<a?(h[b].setOn(),k[b].visible=!0):h[b].setOff();setTimeout(function(){for(var a=0;a<NUM_PAYLINES;a++)k[a].visible=!1},1E3)};this.resetWin=function(){w.text=" "};this.refreshWinText=function(a){w.text=TEXT_WIN+" "+a.toFixed(2)};this.showLine=function(a){k[a-1].visible=!0};this.hideLine=function(a){k[a-1].visible=!1};this.hideAllLines=function(){for(var a=0;a<NUM_PAYLINES;a++)k[a].visible=
!1};this.disableBetBut=function(a){for(var b=0;b<NUM_PAYLINES;b++)h[b].disable(a)};this.enableGuiButtons=function(){f.enable();q.enable();r.enable();b.enable();g.enable()};this.enableSpin=function(){f.enable();q.enable()};this.disableSpin=function(){f.disable();q.disable()};this.disableGuiButtons=function(){f.disable();q.disable();r.disable();b.disable();g.disable()};this._onBetLineClicked=function(a){this.refreshNumLines(a);s_oGame.activateLines(a)};this._onExit=function(){s_oGame.onExit()};this._onSpin=
function(){s_oGame.onSpin()};this._onAddLine=function(){s_oGame.addLine()};this._onInfo=function(){s_oGame.onInfoClicked()};this._onBet=function(){s_oGame.changeCoinBet()};this._onMaxBet=function(){s_oGame.onMaxBet()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};s_oInterface=this;this._init(a,d,e);return this}var s_oInterface;
function CHelpPanel(a){var d,e,h,k;this._init=function(a){h=new createjs.Bitmap(a);e=new createjs.Text(gameText.help1,"bold 21px Arial","#000000");e.textAlign="center";e.x=CANVAS_WIDTH/2+2;e.y=142;d=new createjs.Text(gameText.help1,"bold 21px Arial","#ffffff");d.textAlign="center";d.x=CANVAS_WIDTH/2;d.y=140;a=new createjs.Text(gameText.help2,"bold 19px Arial","#000000");a.textAlign="center";a.x=CANVAS_WIDTH/2+2;a.y=242;var f=new createjs.Text(gameText.help2,"bold 19px Arial","#ffffff");f.textAlign=
"center";f.x=CANVAS_WIDTH/2;f.y=240;k=new createjs.Container;k.addChild(h,e,d,a,f);s_oStage.addChild(k);var g=this;k.on("pressup",function(){g._onExitHelp()})};this.unload=function(){s_oStage.removeChild(k);var a=this;k.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){this.unload();s_oGame._onExitHelp()};this._init(a)}
function CGfxButton(a,d,e){var h,k,c=[],f;this._init=function(a,b,c){h=[];k=[];f=new createjs.Bitmap(c);f.x=a;f.y=b;f.regX=c.width/2;f.regY=c.height/2;s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);s_oStage.removeChild(f)};this.setVisible=function(a){f.visible=a};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;k[a]=
c};this.addEventListenerWithParams=function(a,b,d,e){h[a]=b;k[a]=d;c=e};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");f.scaleX=1;f.scaleY=1;h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP],c)};this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],c)};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};
this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(a,d,e);return this}
function CGame(a){var d=!1,e,h,k,c,f,g,b,t,r,q,m,p,n,v,s,u,w,y,z,l,x=null;this._init=function(){e=GAME_STATE_IDLE;c=h=0;v=[0,1,2,3,4];k=v[0];f=NUM_PAYLINES;q=TOTAL_MONEY;t=MIN_BET;r=t*f;s_oTweenController=new CTweenController;y=new createjs.Bitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(y);this._initReels();z=new createjs.Bitmap(s_oSpriteLibrary.getSprite("mask_slot"));s_oStage.addChild(z);l=new CInterface(t,r,q);this._initStaticSymbols();x=new CPayTablePanel;d=!0};this.unload=function(){createjs.Sound.stop();
s_oStage.removeChild(y);s_oStage.removeChild(z);l.unload();x.unload();for(var a=0;a<m.length;a++)m[a].unload();for(a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)p[a][b].unload()};this._initReels=function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y,c=0;m=[];for(var d=0;d<NUM_REELS;d++)m[d]=new CReelColumn(d,a,b,c),m[d+NUM_REELS]=new CReelColumn(d+NUM_REELS,a,b+SYMBOL_SIZE*NUM_ROWS,c),a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS,c+=REEL_DELAY};this._initStaticSymbols=function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y;
p=[];for(var c=0;c<NUM_ROWS;c++){p[c]=[];for(var d=0;d<NUM_REELS;d++){var e=new CStaticSymbolCell(c,d,a,b);p[c][d]=e;a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS}a=REEL_OFFSET_X;b+=SYMBOL_SIZE}};this.generateFinalSymbols=function(){s=[];for(var a=0;a<NUM_ROWS;a++){s[a]=[];for(var b=0;b<NUM_REELS;b++){var c=Math.floor(Math.random()*s_aRandSymbols.length);s[a][b]=s_aRandSymbols[c]}}n=[];for(a=0;a<f;a++){var b=s_aPaylineCombo[a],c=[],d=s[b[0].row][b[0].col],e=1,g=1;for(c.push({row:b[0].row,col:b[0].col,value:s[b[0].row][b[0].col]});d===
WILD_SYMBOL&&g<NUM_REELS;)e++,d=s[b[g].row][b[g].col],c.push({row:b[g].row,col:b[g].col,value:s[b[g].row][b[g].col]}),g++;for(;g<b.length;g++)if(s[b[g].row][b[g].col]===d||s[b[g].row][b[g].col]===WILD_SYMBOL)e++,c.push({row:b[g].row,col:b[g].col,value:s[b[g].row][b[g].col]});else break;0<s_aSymbolWin[d-1][e-1]&&n.push({line:a+1,amount:s_aSymbolWin[d-1][e-1],num_win:e,value:d,list:c})}};this._generateRandSymbols=function(){for(var a=[],b=0;b<NUM_ROWS;b++){var c=Math.floor(Math.random()*s_aRandSymbols.length);
a[b]=s_aRandSymbols[c]}return a};this.reelArrived=function(a,b){if(h>MIN_REEL_LOOPS)if(k===b){if(!1===m[a].isReadyToStop()){var c=a;a<NUM_REELS?(c+=NUM_REELS,m[c].setReadyToStop(),m[a].restart([s[0][a],s[1][a],s[2][a]],!0)):(c-=NUM_REELS,m[c].setReadyToStop(),m[a].restart([s[0][c],s[1][c],s[2][c]],!0))}}else m[a].restart(this._generateRandSymbols(),!1);else m[a].restart(this._generateRandSymbols(),!1),0===a&&h++};this.stopNextReel=function(){c++;0===c%2&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
createjs.Sound.play("reel_stop"),k=v[c/2],c===2*NUM_REELS&&this._endReelAnimation())};this._endReelAnimation=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||u.stop();l.disableBetBut(!1);c=h=0;k=v[0];var a=0;if(0<n.length){for(var b=0;b<n.length;b++){x.highlightCombo(n[b].value,n[b].num_win);l.showLine(n[b].line);for(var d=n[b].list,f=0;f<d.length;f++)p[d[f].row][d[f].col].show(d[f].value);q+=n[b].amount;a+=n[b].amount}l.refreshMoney(q);l.refreshWinText(a);g=0;e=GAME_STATE_SHOW_ALL_WIN;if(!1===
DISABLE_SOUND_MOBILE||!1===s_bMobile)w=createjs.Sound.play("win",{volume:.3})}else e=GAME_STATE_IDLE;l.enableGuiButtons();q<r&&l.disableSpin();$(s_oMain).trigger("end_bet",[q,a])};this.hidePayTable=function(){x.hide()};this._showWin=function(){var a;if(0<b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||w.stop();a=n[b-1].line;l.hideLine(a);a=n[b-1].list;for(var c=0;c<a.length;c++)p[a[c].row][a[c].col].stopAnim()}b===n.length&&(b=0);a=n[b].line;l.showLine(a);a=n[b].list;for(c=0;c<a.length;c++)p[a[c].row][a[c].col].show(a[c].value);
b++};this._hideAllWins=function(){for(var a=0;a<n.length;a++)for(var c=n[a].list,d=0;d<c.length;d++)p[c[d].row][c[d].col].stopAnim();l.hideAllLines();b=g=0;g=TIME_SHOW_WIN;e=GAME_STATE_SHOW_WIN};this.activateLines=function(a){f=a;this.removeWinShowing();r=a=t*f;l.refreshTotalBet(r);l.refreshNumLines(f);a>q?l.disableSpin():l.enableSpin()};this.addLine=function(){f===NUM_PAYLINES?f=1:f++;var a=t*f;r=a;l.refreshTotalBet(r);l.refreshNumLines(f);a>q?l.disableSpin():l.enableSpin()};this.changeCoinBet=function(){var a=
Math.floor(100*(t+.05))/100;a>MAX_BET?(t=MIN_BET,r=t*f,l.refreshBet(t),l.refreshTotalBet(r),a=r):(a*=f,t+=.05,t=Math.floor(100*t)/100,r=a,l.refreshBet(t),l.refreshTotalBet(r));a>q?l.disableSpin():l.enableSpin()};this.onMaxBet=function(){var a=MAX_BET;f=NUM_PAYLINES;a*=f;t=MAX_BET;r=a;l.refreshBet(t);l.refreshTotalBet(r);l.refreshNumLines(f);a>q?l.disableSpin():(l.enableSpin(),this.onSpin())};this.removeWinShowing=function(){x.resetHighlightCombo();l.resetWin();for(var a=0;a<NUM_ROWS;a++)for(var b=
0;b<NUM_REELS;b++)p[a][b].hide();for(a=0;a<m.length;a++)m[a].activate();e=GAME_STATE_IDLE};this.onSpin=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)w&&w.stop(),u=createjs.Sound.play("reels");l.disableBetBut(!0);this.removeWinShowing();this.generateFinalSymbols();l.hideAllLines();l.disableGuiButtons();q-=r;l.refreshMoney(q);e=GAME_STATE_SPINNING};this.onInfoClicked=function(){e!==GAME_STATE_SPINNING&&(x.isVisible()?x.hide():x.show())};this.onExit=function(){this.unload();s_oMain.gotoMenu();
$(s_oMain).trigger("restart")};this.getState=function(){return e};this.update=function(){if(!1!==d)switch(e){case GAME_STATE_SPINNING:for(var a=0;a<m.length;a++)m[a].update();break;case GAME_STATE_SHOW_ALL_WIN:g+=s_iTimeElaps;g>TIME_SHOW_ALL_WINS&&this._hideAllWins();break;case GAME_STATE_SHOW_WIN:g+=s_iTimeElaps,g>TIME_SHOW_WIN&&(g=0,this._showWin())}};s_oGame=this;MIN_REEL_LOOPS=a.min_reel_loop;REEL_DELAY=a.reel_delay;TIME_SHOW_WIN=a.time_show_win;TIME_SHOW_ALL_WINS=a.time_show_all_wins;TOTAL_MONEY=
a.money;this._init()}var s_oGame,s_oTweenController;
function CEndPanel(a){var d,e,h,k,c,f;this._init=function(a){d=new createjs.Bitmap(a);d.x=0;d.y=0;c=new createjs.Text("","bold 24px Arial","#000");c.x=CANVAS_WIDTH/2+2;c.y=CANVAS_HEIGHT/2-38;c.textAlign="center";k=new createjs.Text("","bold 24px Arial","#ffffff");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2-40;k.textAlign="center";e=new createjs.Text("","bold 16px Arial","#000");e.x=CANVAS_WIDTH/2+1;e.y=CANVAS_HEIGHT/2+11;e.textAlign="center";h=new createjs.Text("","bold 16px Arial","#ffffff");h.x=CANVAS_WIDTH/
2;h.y=CANVAS_HEIGHT/2+10;h.textAlign="center";f=new createjs.Container;f.alpha=0;f.visible=!1;f.addChild(d,e,h,c,k);s_oStage.addChild(f)};this.unload=function(){f.off("mousedown",this._onExit);s_oStage.removeChild(f)};this._initListener=function(){f.on("mousedown",this._onExit)};this.show=function(a,b){b?(c.text=TEXT_CONGRATS,k.text=TEXT_CONGRATS):(c.text=TEXT_GAMEOVER,k.text=TEXT_GAMEOVER);e.text=TEXT_SCORE+": "+a;h.text=TEXT_SCORE+": "+a;f.visible=!0;var d=this;createjs.Tween.get(f).to({alpha:1},
500).call(function(){d._initListener()})};this._onExit=function(){f.off("mousedown");s_oGame.onExit()};this._init(a);return this}
function CBetBut(a,d,e){var h,k,c,f=[],g;this._init=function(a,d,e){h=!1;k=[];c=[];e=s_oSpriteLibrary.getSprite("bet_but");var f=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:0,regY:0},animations:{on:[0,1],off:[1,2]}});g=new createjs.Sprite(f,"on");g.stop();g.x=a;g.y=d;g.regX=e.width/2;g.regY=e.height/2;s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);s_oStage.removeChild(g)};
this.disable=function(a){h=a};this.setVisible=function(a){g.visible=a};this.setOn=function(){g.gotoAndStop("on")};this.setOff=function(){g.gotoAndStop("off")};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,d,e){k[a]=d;c[a]=e};this.addEventListenerWithParams=function(a,d,e,g){k[a]=d;c[a]=e;f=g};this.buttonRelease=function(){k[ON_MOUSE_UP]&&!1===h&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),
k[ON_MOUSE_UP].call(c[ON_MOUSE_UP],f))};this.buttonDown=function(){k[ON_MOUSE_DOWN]&&!1===h&&k[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN],f)};this.setPosition=function(a,c){g.x=a;g.y=c};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};this._init(a,d,e)};